= Como escolher um curso de computação
:toc: left
:toclevels: 1
:language: asciidoc
:docref: link:/docs

Esse é um panfleto que busca te auxiliar a escolher um curso para entrar no mercado de desenvolvimento de software. 
Nós, brasileiros, aprendemos que podemos estudar faz poucos anos, muitos dos nossos somos os primeiros das nossas 
famílias a sentar em uma cadeira de universidade. Isso é extremamente possitivo, mas a falta de cultura de estudo 
podem trazer algumas armadilhas que queremos desarmar com esse panfleto.

Todo colaboração é bem vinda, por isso dê sugestões, revise o texto, adicione questões. Esse é um trabalho colaborativo.

== Diferença entre Faculdade e Cursos Livres

Antes de tudo quero advogar que sou a favor de Faculdades e de Cursos Livres. Ambos tem sua validade, mas ambos tem o 
seu contexto. Não existe uma competição entre os dois tipos de formação.

Cursos Livres são focados em tecnicas especificas, servem para atualizar alguns conteúdos, mas não tem a preocupação de oferecer uma base sólida para que o aluno possa se tornar plenamente suficiente no assunto.

Já universidades tem um amplo papel social. Seu papel vai muito além de apenas formar profissionais. Segundo o professor Hernan Chaimovich "_universidades públicas têm uma missão que compreende formar pessoas capacitadas para alavancar um País inteiro_" ^https://jornal.usp.br/atualidades/universidade-publica-tem-papel-social-intelectual-e-economico/[[1]]^.

> De acordo com o ex-pró-reitor da USP (_professor Hernan Chaimovich_), as universidades públicas têm uma missão que compreende formar pessoas capacitadas para alavancar um País inteiro. Além disso, as universidades públicas, “especialmente no Brasil, têm uma responsabilidade única de produzir conhecimentos e fazer com que esses conhecimentos tragam benefício social, intelectual e econômico para a sociedade”. Ele diz que essas duas responsabilidades bastariam para colocar a Universidade como um dos pilares da sociedade brasileira, e ressalta que o termo universidade pública não diz respeito à gratuidade: “Não é gratuita, porque é paga pelos contribuintes do País todo. E, portanto, essa transferência de fundos para construir uma responsabilidade requer um equilíbrio que precisa ser mantido com absoluta autonomia da Universidade”.

Por isso é bem comum vermos universidade públicas focadas em cursos de extensão e programas de pesquisas. Muito conhecimento e tecnologia são produzidos dentro de uma universidade e eles são úteis a toda sociedade. Um programa interessante que existe nas universidade públicas são os cursos de extensão que, na maioria dos casos, são gratuitos.

Já o professor Renato Janine afirma que a universidade deve estar compromissada com a vida futura do aluno, em 2003 ele escreveu um texto defendendo que os alunos ao entrar na universidade deveria ter a liberdade de escolha da grade curricular dentro de um curriculo de humanidades com o intuíto de preparar eles para o mercado de trabalho 20 ou 30 anos depois do ingresso ^https://www.comciencia.br/dossies-1-72/reportagens/universidades/uni10.shtml[[2]]^.

Se você tem uma visão mais conservadora e acha que as universidades são lugares de balbúrdia, eu lhe recomendo duas atividades. A primeira é conhecer uma universidade além da hora da entrada. Você verá uma série de projetos de pesquisas, professores empenhados em auxiliar seus alunos, produção de conteúdo e conhecimento. Eu falei "hora da entrada" porque toda instituição de ensino tem um certo grau de "balbúrdia" simplesmente por ter todo tipo de aluno na faixa dos 20 e poucos anos. Isso é comum tanto em universidades públicas e privadas. 

Ainda da visão conservadora, eu ressaldo a visão de um filosofo conservador que defende que a universidade deve ser livre pensar e questionar, pois é lá que são formada a nova geração de pensadores da sociedade. O texto erra ao afirmar que toda forma de pensar deve ser aceita, essa liberdade, já vimos é amplamente usada para defeder ideias supremacistas. Creio que ele não concorda com o https://pt.wikipedia.org/wiki/Paradoxo_da_toler%C3%A2ncia["Paradoxo da tolerância"] de Karl Popper.

> "Temos universidades dedicadas a expansão do conhecimento, que não são meramente não-elitistas, mas anti-elitistas em sua estrutura social. Eles não fazem discriminação por motivos de religião, sexo, raça ou classe. São lugares de pesquisa e questionamento de mente-aberta, lugares sem compromissos dogmáticos, cujo propósito é o avanço do conhecimento através de um espírito de livre investigação. Este espírito é transmitido aos seus alunos, que têm a mais ampla escolha de currículo e adquirem conhecimentos que não são apenas firmemente fundamentados, mas eminentemente úteis em suas vidas futuras: administração de empresas, por exemplo, administração hoteleira ou relações internacionais. Em suma, as universidades evoluíram de clubes socialmente exclusivos, para o estudo de futilidades preciosas, para centros de treinamento socialmente inclusivos, para a propagação de habilidades necessárias. E a cultura que eles transmitem não é de uma elite privilegiada, mas de uma “cultura inclusiva” que qualquer um pode adquirir e desfrutar."

Com essas três visões podemos afirmar que Universidade é muito mais do que apenas uma formação técnica.

== Faculdades são desatualizadas?

Resposta simples: Não!

Agora vamos a resposta complexa...

**TODO**

== Reconhecida x Autorizada pelo MEC

Diversas Universidades principalmente as que estão começando (principalmente as que antes eram empresas de cursos 
livres) usam o termo "Autorizada pelo MEC" como meio de propagando, uma forma de demonstrar confiabilidade, porém
é importante notar que **todo curso superior deve ser autorizado pelo MEC** sem exceção, ponto. Um curso que não é
autorizado pelo MEC não pode ser considerado como Ensino Superior. É possível consultar quais cursos são autorizados
pelo https://emec.mec.gov.br/[MEC].

Dito isso, é importante saber que *autorizada* e *reconhecida* são termos diferentes e que implicam em níveis diferentes
de reconhecimento do Curso que você está se matriculando. A partir do momento que uma instituição é aprovada para ministrar
qualquer curso de ensino superior o curso é *autorizado* isso significa que ainda é um curso novo e sequer passou por qualquer
avaliação de desempenho ou pelas avaliações do  Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira Legislação 
e Documentos (INEP) que faz a avaliação do currículo, infraestrutura, professores e demais pontos a respeito daquele curso.

Para ser *reconhecida* pelo MEC a instituição de ensino tem que solicitar essa avaliação após ter pelo menos o tempo mínimo
de funcionamento de 50% da carga total do curso, somente após ser aprovada nas citadas avaliações é que então o curso passa
a receber o reconhecimento do MEC e os diplomas expedidos por essa instituição passam a ter reconhecimento.

## Como avaliar uma faculdade?

**TODO**

== Diferença entre as diferentes titulações

Várias vezes as pessoas se perguntam se há diferença entre fazer Bacharelado, Licencicatura ou Tecnólogo e isso
é bastante compreensível uma vez que existe diferença entre custos e tempo de conclusão entre eles que varia em
cada Instituição de Ensino Superior. Porém, é bastante tranquilo de entender as diferenças e vamos explicar aqui
como você pode escolher a melhor opção para seus objetivos.

=== Licenciatura

É a titulação que forma pessoas habilitadas a dar aula. Os formados em Licenciatura podem atuar como professores
na rede pública e ou particular em qualquer curso de Ensino Fundamental, Ensino Médio, Pedagógico ou outras atividades
de ensino que estejam dentro desse escopo por isso é normal que haja o estudo de cadeiras de Pedagogia junto a grade. 
Para essas atividades é *necessário* o diploma de Licenciatura e caso esse seja seu objetivo essa será a escolha natural. 
A maioria das Universidades que oferece essa modalidade para Informática chama o curso simplesmente de "Licenciatura em 
Informática" ou "Licenciatura em Computação", mas pode ser encontrado também como "Licenciatura em Informática na Educação" 
ou similares e geralmente tem  a duração de 4 anos.

=== Bacharelado

São cursos voltados para a formação de profissionais voltados para a pesquisa e atuação no mercado de trabalho, a 
maioria dos cursos "tradicionais" como Engenharia de Software ou Ciência da Computação são cursos dessa categoria.
Esses cursos tem uma carga *teórica* maior e são mais abrangentes que os outros cursos podendo conter mais tópicos
e assuntos mais abrangentes. É o tipo de formação mais indicada para quem pretende seguir na Pós-graduação stricto
sensu (Mestrado e Doutorado) ou tem interesse em assuntos de forma mais abrangente / aprofundada / teórica. Existem
vários cursos de Bacharelado com diferentes finalidades dentro da área de Tecnologia da Informação entre eles Sistemas
de Informação, Bacharelado em Ciência de Dados, Engenharia de Software, os já citados Engenharia da Computação e Ciência
da Computação, além de muitos outros e cada um tende a ter mais foco em diferentes áreas e abordando diferentes conteúdos. 
A duração de Bacharelados pode ser de 4 a 6 anos dependendo do curso e formação.

=== Tecnólogo

São cursos voltados para a formação de profissioanis voltados a atuação de nichos do mercado de trabalho e tendem a
ter uma carga de estudo mais voltado para a *prática* e para as questões mais técnicas. Por se tratar de uma formação
de Ensino Superior como todas as demais também habilita para que o aluno siga na Pós-graduação após a conclusão ou participe
de concursos que exigam Ensino Superior. É o tipo de formação mais indicada para quem quer desenvolver competências técnicas
e atuar como profissional no mercado uma vez em que os cursos são direcionados a essa finalidade. Existem muitos técnologos
em diferentes nichos da área de Tecnologia da Informação, entre eles os cursos de Tecnólogo em Redes, Tecnólogo em Análise e
Desenvolvimento de Sistemas, Técnologo em Jogos, Técnologo em Mídias Digitais e muitas outras opções. Os cursos de tecnologia
tem duração entre 2 a 3 anos.
